version: "2"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    container_name: server
    volumes:
      - ./:/device-detector
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
  php:
    image: php:fpm
    volumes:
      - ./:/device-detector
    container_name: device-detector
    networks:
      - code-network
networks:
  code-network:
    driver: bridge
